### ISSUE TITLE
Add fileds to supplier

### ISSUE THREAD

**Issue by BrunoMollo** [BrunoMollo/Bocantino-ERP#62]
En la ficha de carga de proveedores, habría que agregar unos campos: 
- persona de contacto 
- ⁠celular 
- ⁠Y si es posible uno donde se puedan agregar comentarios.
Abrazo, buen fin de semana

**Comment by BianconiFilippo** [comment]
Solve

**Comment by BrunoMollo** [comment]
Solved in PR #69
